version: '3.1'
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: ybenlafk
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
#     volumes:
#       - postg:/var/lib/postgresql/data

# volumes:
#   postg:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /goinfre/mjarboua/back/data/